'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,BookOpen,Check,CircleHelp,Eraser,Gamepad2,Home,Lightbulb,RotateCcw,Sparkles,Star,Trophy,Volume2,VolumeX,X} from 'lucide-react';
type Screen='home'|'words'|'sentences'|'builder'|'progress';
const words=[['family','משפחה','👨‍👩‍👧‍👦'],['friend','חבר/ה','🤝'],['school','בית ספר','🏫'],['teacher','מורה','👩‍🏫'],['book','ספר','📘'],['pencil','עיפרון','✏️'],['house','בית','🏠'],['room','חדר','🛏️'],['kitchen','מטבח','🍳'],['breakfast','ארוחת בוקר','🥣'],['water','מים','💧'],['fruit','פרי','🍎'],['animal','בעל חיים','🐾'],['cat','חתול','🐈'],['dog','כלב','🐕'],['happy','שמח/ה','😊'],['tired','עייף/ה','😴'],['excited','נרגש/ת','🤩'],['play','לשחק','⚽'],['read','לקרוא','📖'],['write','לכתוב','📝'],['drink','לשתות','🥤'],['eat','לאכול','🍽️'],['walk','ללכת','🚶'],['morning','בוקר','🌅'],['evening','ערב','🌇'],['today','היום','📅'],['sunny','שמשי','☀️'],['rainy','גשום','🌧️'],['weekend','סוף שבוע','🎈']] as const;
const levels=[[{q:'The cat ___ the milk.',a:['drank','played','blue','table'],c:'drank',e:'drank = שתה'},{q:'Dana reads a ___ every evening.',a:['book','rainy','walk','happy'],c:'book',e:'book = ספר'},{q:'We go to ___ in the morning.',a:['school','fruit','tired','drink'],c:'school',e:'school = בית ספר'},{q:'The weather is ___ today.',a:['sunny','pencil','kitchen','read'],c:'sunny',e:'sunny = שמשי'}],[{q:'My ___ is very ___.',a:['friend · happy','book · rainy','water · tired','cat · school'],c:'friend · happy',e:'My friend is very happy = החבר/ה שלי שמח/ה מאוד'},{q:'I ___ fruit in the ___.',a:['eat · morning','write · kitchen','play · book','drink · teacher'],c:'eat · morning',e:'I eat fruit in the morning = אני אוכל/ת פרי בבוקר'},{q:'The ___ is in the ___.',a:['dog · room','sunny · water','evening · play','read · family'],c:'dog · room',e:'The dog is in the room = הכלב בחדר'}],[{q:'We ___ with our ___ every ___.',a:['play · friends · weekend','drink · books · sunny','write · cats · water','eat · school · tired'],c:'play · friends · weekend',e:'We play with our friends every weekend = אנחנו משחקים עם החברים בכל סוף שבוע'},{q:'My ___ reads a ___ at ___.',a:['teacher · book · school','fruit · dog · rainy','room · pencil · happy','water · family · play'],c:'teacher · book · school',e:'My teacher reads a book at school = המורה שלי קוראת ספר בבית הספר'}]];
const builds=[{he:'החתול שתה את החלב',t:['The','cat','drank','the','milk'],x:['dog','eats','blue']},{he:'אני קוראת ספר בכל ערב',t:['I','read','a','book','every','evening'],x:['drink','school','sunny']},{he:'החברה שלי משחקת עם הכלב',t:['My','friend','plays','with','the','dog'],x:['cat','reads','morning']},{he:'אנחנו אוכלים פירות במטבח',t:['We','eat','fruit','in','the','kitchen'],x:['write','room','rainy']}];
const extraWords:[string,string,string][]=[
['parents','הורים','👪'],['sister','אחות','👧'],['brother','אח','👦'],['grandmother','סבתא','👵'],['grandfather','סבא','👴'],
['student','תלמיד/ה','🎒'],['lesson','שיעור','📋'],['homework','שיעורי בית','📚'],['question','שאלה','❓'],['answer','תשובה','✅'],
['computer','מחשב','💻'],['window','חלון','🪟'],['garden','גינה','🌷'],['street','רחוב','🛣️'],['library','ספרייה','📚'],
['bread','לחם','🍞'],['cheese','גבינה','🧀'],['vegetable','ירק','🥕'],['dinner','ארוחת ערב','🍲'],['hungry','רעב/ה','😋'],
['bird','ציפור','🐦'],['horse','סוס','🐴'],['rabbit','ארנב','🐇'],['forest','יער','🌲'],['river','נהר','🏞️'],
['beautiful','יפה','🌟'],['difficult','קשה','🧗'],['easy','קל','👌'],['important','חשוב','❗'],['interesting','מעניין','🔎'],
['run','לרוץ','🏃'],['swim','לשחות','🏊'],['listen','להקשיב','🎧'],['speak','לדבר','💬'],['learn','ללמוד','🧠'],
['yesterday','אתמול','⏪'],['tomorrow','מחר','⏩'],['usually','בדרך כלל','🔁'],['sometimes','לפעמים','🎲'],['always','תמיד','♾️'],
['cloudy','מעונן','☁️'],['windy','סוער ברוחות','🌬️'],['winter','חורף','❄️'],['summer','קיץ','🏖️'],['season','עונה','🍂'],
['music','מוזיקה','🎵'],['movie','סרט','🎬'],['bicycle','אופניים','🚲'],['holiday','חופשה','🧳'],['journey','מסע','🗺️']];
(words as unknown as [string,string,string][]).push(...extraWords);

const moreLevel1=[
{q:'My sister rides her ___ to school.',a:['bicycle','window','dinner','cloudy'],c:'bicycle',e:'bicycle = אופניים'},
{q:'We borrow books from the ___.',a:['library','river','breakfast','street'],c:'library',e:'library = ספרייה'},
{q:'I do my ___ after school.',a:['homework','cheese','summer','bird'],c:'homework',e:'homework = שיעורי בית'},
{q:'The rabbit lives in the ___.',a:['forest','computer','lesson','bread'],c:'forest',e:'forest = יער'},
{q:'Please ___ to the teacher.',a:['listen','swim','eat','rainy'],c:'listen',e:'listen = להקשיב'},
{q:'The test was not difficult; it was ___.',a:['easy','windy','hungry','important'],c:'easy',e:'easy = קל'},
{q:'We eat ___ with our salad.',a:['cheese','movie','question','winter'],c:'cheese',e:'cheese = גבינה'},
{q:'It is cold and snowy in ___.',a:['winter','summer','morning','journey'],c:'winter',e:'winter = חורף'},
{q:'I will visit my grandmother ___.',a:['tomorrow','yesterday','always','room'],c:'tomorrow',e:'tomorrow = מחר'},
{q:'The pupils asked an interesting ___.',a:['question','garden','water','horse'],c:'question',e:'question = שאלה'},
{q:'She can ___ very fast.',a:['run','write','book','family'],c:'run',e:'run = לרוץ'},
{q:'My favorite subject is ___.',a:['English','kitchen','rabbit','drink'],c:'English',e:'English = אנגלית'},
{q:'The flowers grow in the ___.',a:['garden','street','computer','teacher'],c:'garden',e:'garden = גינה'},
{q:'We watch a ___ on Friday.',a:['movie','pencil','fruit','season'],c:'movie',e:'movie = סרט'},
{q:'The children are ___ after the long walk.',a:['tired','sunny','bread','school'],c:'tired',e:'tired = עייפים'},
{q:'Can you ___ English?',a:['speak','river','beautiful','today'],c:'speak',e:'speak = לדבר'},
{q:'The ___ is flying above the tree.',a:['bird','horse','cat','vegetable'],c:'bird',e:'bird = ציפור'},
{q:'Breakfast is an ___ meal.',a:['important','rainy','easy','cloudy'],c:'important',e:'important = חשוב'},
{q:'We went to the beach last ___.',a:['summer','winter','lesson','answer'],c:'summer',e:'summer = קיץ'},
{q:'The story was very ___.',a:['interesting','hungry','windy','pencil'],c:'interesting',e:'interesting = מעניין'}];
const moreLevel2=[
{q:'My ___ uses a ___.',a:['brother · computer','river · dinner','teacher · cloudy','bread · bicycle'],c:'brother · computer',e:'My brother uses a computer = אחי משתמש במחשב'},
{q:'We ___ in the ___.',a:['swim · river','write · winter','eat · library','listen · street'],c:'swim · river',e:'We swim in the river = אנחנו שוחים בנהר'},
{q:'The ___ is very ___.',a:['garden · beautiful','question · hungry','cheese · windy','movie · difficult'],c:'garden · beautiful',e:'The garden is very beautiful = הגינה יפה מאוד'},
{q:'I ___ my homework ___.',a:['usually do · evening','always eat · river','sometimes swim · book','today read · kitchen'],c:'usually do · evening',e:'I usually do my homework in the evening'},
{q:'My ___ tells an interesting ___.',a:['grandfather · story','computer · season','rabbit · answer','breakfast · movie'],c:'grandfather · story',e:'My grandfather tells an interesting story'},
{q:'It is ___ and ___.',a:['cloudy · windy','book · happy','summer · pencil','fruit · difficult'],c:'cloudy · windy',e:'It is cloudy and windy = מעונן וסוער'},
{q:'The ___ gave the correct ___.',a:['student · answer','horse · dinner','window · lesson','garden · bicycle'],c:'student · answer',e:'The student gave the correct answer'},
{q:'We ___ music at ___.',a:['listen to · home','swim in · school','eat · tomorrow','write · forest'],c:'listen to · home',e:'We listen to music at home'},
{q:'My ___ is in the ___.',a:['pencil · bag','summer · library','bread · river','lesson · garden'],c:'pencil · bag',e:'My pencil is in the bag'},
{q:'They ___ English every ___.',a:['learn · day','drink · winter','play · question','eat · window'],c:'learn · day',e:'They learn English every day'},
{q:'The ___ runs very ___.',a:['horse · fast','movie · hungry','room · sunny','teacher · fruit'],c:'horse · fast',e:'The horse runs very fast'},
{q:'I ate ___ for ___.',a:['bread · breakfast','computer · dinner','street · summer','homework · morning'],c:'bread · breakfast',e:'I ate bread for breakfast'},
{q:'We visit our ___ on ___.',a:['grandparents · weekends','students · rivers','teachers · winters','friends · homework'],c:'grandparents · weekends',e:'We visit our grandparents on weekends'},
{q:'She ___ a beautiful ___.',a:['wrote · story','drank · street','ate · season','ran · question'],c:'wrote · story',e:'She wrote a beautiful story'},
{q:'The ___ is open ___.',a:['library · today','rabbit · always','fruit · tomorrow','movie · difficult'],c:'library · today',e:'The library is open today'}];
const moreLevel3=[
{q:'My ___ ___ to school every ___.',a:['sister · walks · morning','teacher · drinks · winter','rabbit · writes · dinner','computer · runs · book'],c:'sister · walks · morning',e:'My sister walks to school every morning'},
{q:'We ___ an ___ movie ___.',a:['watched · interesting · yesterday','ate · sunny · tomorrow','read · hungry · always','played · cloudy · school'],c:'watched · interesting · yesterday',e:'We watched an interesting movie yesterday'},
{q:'The ___ ___ in the green ___.',a:['rabbit · plays · garden','student · swims · pencil','bird · writes · kitchen','horse · reads · water'],c:'rabbit · plays · garden',e:'The rabbit plays in the green garden'},
{q:'Our ___ gives us ___ ___.',a:['teacher · difficult · homework','cat · windy · cheese','brother · rainy · river','friend · hungry · computer'],c:'teacher · difficult · homework',e:'Our teacher gives us difficult homework'},
{q:'I ___ ___ with my ___.',a:['ride · bicycles · friends','eat · lessons · parents','listen · rivers · sister','write · gardens · dog'],c:'ride · bicycles · friends',e:'I ride bicycles with my friends'},
{q:'They ___ ___ in the ___.',a:['speak · English · lesson','drink · movies · forest','play · cheese · window','read · summer · water'],c:'speak · English · lesson',e:'They speak English in the lesson'},
{q:'The ___ is ___ and ___.',a:['weather · sunny · warm','book · hungry · cloudy','river · important · tired','answer · difficult · windy'],c:'weather · sunny · warm',e:'The weather is sunny and warm'},
{q:'My ___ prepared ___ for ___.',a:['mother · vegetables · dinner','teacher · homework · breakfast','rabbit · pencils · summer','friend · windows · school'],c:'mother · vegetables · dinner',e:'My mother prepared vegetables for dinner'},
{q:'We ___ our ___ every ___.',a:['visit · grandparents · weekend','drink · library · winter','write · bicycle · evening','eat · teacher · question'],c:'visit · grandparents · weekend',e:'We visit our grandparents every weekend'},
{q:'The ___ ___ above the ___.',a:['bird · flies · river','horse · reads · window','student · eats · forest','cat · speaks · lesson'],c:'bird · flies · river',e:'The bird flies above the river'},
{q:'She ___ to ___ music ___.',a:['likes · listen to · daily','runs · eat · winter','writes · swim · hungry','drinks · play · difficult'],c:'likes · listen to · daily',e:'She likes to listen to music daily'},
{q:'Our ___ was ___ and ___.',a:['journey · long · interesting','cheese · cloudy · easy','pencil · warm · hungry','answer · sunny · tired'],c:'journey · long · interesting',e:'Our journey was long and interesting'},
{q:'I ___ the ___ answer ___.',a:['found · correct · quickly','ate · difficult · tomorrow','drank · sunny · always','played · cloudy · school'],c:'found · correct · quickly',e:'I found the correct answer quickly'},
{q:'They ___ ___ near the ___.',a:['played · football · school','read · dinner · bicycle','swam · homework · kitchen','ate · winter · teacher'],c:'played · football · school',e:'They played football near the school'},
{q:'My ___ will ___ us ___.',a:['parents · visit · tomorrow','bird · write · yesterday','lesson · eat · always','river · speak · difficult'],c:'parents · visit · tomorrow',e:'My parents will visit us tomorrow'}];
levels[0].push(...moreLevel1);levels[1].push(...moreLevel2);levels[2].push(...moreLevel3);
levels.forEach((level,levelIndex)=>level.forEach((question,questionIndex)=>{const shift=(questionIndex+levelIndex)%question.a.length;question.a.push(...question.a.splice(0,shift))}));

builds.push(
{he:'אחותי רוכבת על אופניים לבית הספר',t:['My','sister','rides','a','bicycle','to','school'],x:['brother','reads','river']},
{he:'אנחנו מבקרים את סבא וסבתא בסוף השבוע',t:['We','visit','our','grandparents','on','the','weekend'],x:['teacher','eat','sunny']},
{he:'הארנב הקטן משחק בגינה',t:['The','little','rabbit','plays','in','the','garden'],x:['bird','drinks','library']},
{he:'אני תמיד מכינה שיעורי בית בערב',t:['I','always','do','my','homework','in','the','evening'],x:['sometimes','swim','breakfast']},
{he:'מזג האוויר היום מעונן וסוער',t:['The','weather','is','cloudy','and','windy','today'],x:['winter','beautiful','reads']},
{he:'אחי אוהב לשחק במחשב',t:['My','brother','likes','to','play','on','the','computer'],x:['sister','eat','horse']},
{he:'המורה שאלה שאלה מעניינת',t:['The','teacher','asked','an','interesting','question'],x:['answered','dinner','summer']},
{he:'אנחנו שוחים בנהר בקיץ',t:['We','swim','in','the','river','in','summer'],x:['winter','walk','movie']},
{he:'הציפור עפה מעל היער',t:['The','bird','flies','above','the','forest'],x:['rabbit','writes','kitchen']},
{he:'הילדים הקשיבו למוזיקה',t:['The','children','listened','to','music'],x:['homework','drank','cloudy']},
{he:'המסע שלנו היה ארוך ומעניין',t:['Our','journey','was','long','and','interesting'],x:['short','hungry','pencil']},
{he:'מחר נאכל ארוחת בוקר בגינה',t:['Tomorrow','we','will','eat','breakfast','in','the','garden'],x:['yesterday','library','swim']}
);
const TOTAL_ACTIVITIES=words.length+levels.flat().length+builds.length;
const initial={score:0,wordsSeen:0,completed:[] as string[],streak:0};type Stats=typeof initial;
export default function Page(){const[screen,setScreen]=useState<Screen>('home'),[stats,setStats]=useState(initial),[sound,setSound]=useState(true),[help,setHelp]=useState(false);useEffect(()=>{const s=localStorage.getItem('wordventure-progress');if(s)setStats({...initial,...JSON.parse(s)})},[]);useEffect(()=>localStorage.setItem('wordventure-progress',JSON.stringify(stats)),[stats]);const reward=(p:number,k:string)=>setStats(s=>({...s,score:s.score+p,streak:s.streak+1,completed:s.completed.includes(k)?s.completed:[...s.completed,k]}));return <main dir="rtl" className="app"><header><button className="brand" onClick={()=>setScreen('home')}><i><Sparkles/></i><span><b>WordVenture</b><small>הרפתקה באנגלית</small></span></button><nav><span><Star fill="currentColor"/> {stats.score}</span><span>🔥 {stats.streak}</span><button onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}</button><button onClick={()=>setHelp(true)}><CircleHelp/></button></nav></header>{screen==='home'&&<HomePage s={stats} go={setScreen}/>} {screen==='words'&&<Words s={stats} set={setStats} reward={reward} back={()=>setScreen('home')}/>} {screen==='sentences'&&<Sentences reward={reward} back={()=>setScreen('home')}/>} {screen==='builder'&&<Builder reward={reward} back={()=>setScreen('home')}/>} {screen==='progress'&&<Progress s={stats} reset={()=>setStats(initial)} back={()=>setScreen('home')}/>} {help&&<div className="shade" onClick={()=>setHelp(false)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setHelp(false)}><X/></button><div>💡</div><h2>איך משחקים?</h2><p>בוחרים משימה, פותרים בקצב שלך וצוברים כוכבים. טעית? לא נורא — מקבלים רמז ומנסים שוב.</p><button className="primary" onClick={()=>setHelp(false)}>הבנתי, מתחילים!</button></section></div>}</main>}
function HomePage({s,go}:{s:Stats;go:(v:Screen)=>void}){const p=Math.min(100,Math.round(s.completed.length/TOTAL_ACTIVITIES*100));return <div className="home"><section className="hero"><div><label>המסע שלך באנגלית</label><h1>מוכנה להרפתקה<br/><em>חדשה?</em></h1><p>לומדים מילים, משלימים משפטים וצוברים כוכבים — בקצב שלך.</p><button className="primary yellow" onClick={()=>go('words')}>ממשיכים ללמוד <ArrowLeft/></button></div><aside><b>HELLO</b><strong>🦊</strong><span>📖</span><b>WOW!</b></aside></section><div className="section-title"><div><label>מפת המסע</label><h2>במה נשחק היום?</h2></div><button onClick={()=>go('progress')}>ההתקדמות שלי ←</button></div><section className="cards"><Card n="01" icon="📚" title="אוצר מילים" text="מכירים 80 מילים חדשות בעזרת כרטיסיות ומשחקים." meta={`${Math.min(s.wordsSeen,words.length)} מתוך ${words.length} מילים`} c="yellowCard" go={()=>go('words')}/><Card n="02" icon="🧩" title="משלימים משפטים" text="בוחרים את המילים הנכונות ומשלימים את המשפט." meta={`${levels.flat().length} שאלות בשלוש רמות`} c="aqua" go={()=>go('sentences')}/><Card n="03" icon="🚀" title="בונים משפט" text="מסדרים מילים באנגלית לפי המשפט בעברית." meta={`${builds.length} אתגרי בניית משפט`} c="coral" go={()=>go('builder')}/></section><section className="strip"><i>🏆</i><div><b>התקדמות מצוינת!</b><small>כל תרגיל מקרב אותך אל היעד</small></div><div className="bar"><i style={{width:`${p}%`}}/></div><strong>{p}%</strong></section></div>}
function Card({n,icon,title,text,meta,c,go}:{n:string;icon:string;title:string;text:string;meta:string;c:string;go:()=>void}){return <button className={'card '+c} onClick={go}><small>{n}</small><i>{icon}</i><h3>{title}</h3><p>{text}</p><span>{meta}</span><b>←</b></button>}
function Head({title,step,back}:{title:string;step:string;back:()=>void}){return <div className="gameHead"><button onClick={back}><Home/> חזרה למפה</button><div><label>{step}</label><h1>{title}</h1></div><i/></div>}
function Meter({now,total,label}:{now:number;total:number;label:string}){return <div className="meter"><span>{label} {now} מתוך {total}</span><div><i style={{width:`${now/total*100}%`}}/></div></div>}
function Words({s,set,reward,back}:{s:Stats;set:React.Dispatch<React.SetStateAction<Stats>>;reward:(p:number,k:string)=>void;back:()=>void}){const[i,setI]=useState(0),[flip,setFlip]=useState(false),[mode,setMode]=useState<'cards'|'quiz'>('cards'),[fb,setFb]=useState<'ok'|'no'|null>(null);const w=words[i],choices=useMemo(()=>[w[1],...words.filter((_,j)=>j!==i).slice(i%(words.length-4),i%(words.length-4)+3).map(x=>x[1])].sort(()=>.5-Math.random()),[i,w]);const next=()=>{setI((i+1)%words.length);setFlip(false);setFb(null);set(x=>({...x,wordsSeen:Math.max(x.wordsSeen,i+1)}))};const answer=(a:string)=>{if(fb)return;if(a===w[1]){setFb('ok');reward(10,`word-${i}`)}else{setFb('no');set(s=>({...s,streak:0}));setTimeout(()=>setFb(null),850)}};return <section className="play"><Head title="אוצר מילים" step="שלב 1" back={back}/><div className="tabs"><button className={mode==='cards'?'on':''} onClick={()=>setMode('cards')}>כרטיסיות</button><button className={mode==='quiz'?'on':''} onClick={()=>setMode('quiz')}>בוחרים תשובה</button></div><Meter now={i+1} total={words.length} label="מילה"/>{mode==='cards'?<div className="center"><button className={'flash '+(flip?'flipped':'')} onClick={()=>setFlip(!flip)}><i>{w[2]}</i><small>{flip?'הפירוש בעברית':'המילה באנגלית'}</small><strong dir={flip?'rtl':'ltr'}>{flip?w[1]:w[0]}</strong><span><RotateCcw/> לחצי כדי להפוך</span></button><button className="primary" onClick={next}>למילה הבאה <ArrowLeft/></button></div>:<section className="quiz"><i>{w[2]}</i><span>מה פירוש המילה?</span><h2 dir="ltr">{w[0]}</h2><div className="answers">{choices.map(c=><button key={c} onClick={()=>answer(c)} className={fb&&c===w[1]?'correct':''}>{c}</button>)}</div>{fb&&<p className={'feedback '+fb}>{fb==='ok'?'✨ מצוין! תשובה נכונה':'כמעט! נסי שוב'}</p>}{fb==='ok'&&<button className="primary" onClick={next}>לשאלה הבאה <ArrowLeft/></button>}</section>}</section>}
function Sentences({reward,back}:{reward:(p:number,k:string)=>void;back:()=>void}){const[l,setL]=useState(0),[i,setI]=useState(0),[fb,setFb]=useState<'ok'|'no'|null>(null),cur=levels[l][i];const answer=(a:string)=>{if(fb)return;if(a===cur.c){setFb('ok');reward(15,`sentence-${l}-${i}`)}else{setFb('no');setTimeout(()=>setFb(null),1000)}};const next=()=>{setFb(null);if(i<levels[l].length-1)setI(i+1);else if(l<2){setL(l+1);setI(0)}else{setL(0);setI(0)}};return <section className="play"><Head title="משלימים משפטים" step="שלב 2" back={back}/><div className="levels">{[0,1,2].map(x=><button key={x} className={l===x?'on':''} onClick={()=>{setL(x);setI(0);setFb(null)}}>רמה {x+1}<small>{x+1} {x?'מילים חסרות':'מילה חסרה'}</small></button>)}</div><Meter now={i+1} total={levels[l].length} label="שאלה"/><section className="quiz sentence"><span>בחרי את התשובה שמשלימה את המשפט</span><h2 dir="ltr">{cur.q}</h2><div className="answers english">{cur.a.map((a,j)=><button dir="ltr" key={a} className={fb&&a===cur.c?'correct':''} onClick={()=>answer(a)}><b>{String.fromCharCode(65+j)}</b>{a}</button>)}</div>{fb&&<p className={'feedback '+fb}>{fb==='ok'?`✨ נהדר! ${cur.e}`:'זה לא מתאים למשפט. נסי אפשרות אחרת'}</p>}{fb==='ok'&&<button className="primary" onClick={next}>ממשיכים <ArrowLeft/></button>}</section></section>}
function Builder({reward,back}:{reward:(p:number,k:string)=>void;back:()=>void}){const[i,setI]=useState(0),[placed,setPlaced]=useState<string[]>([]),[fb,setFb]=useState<'ok'|'no'|null>(null),[hint,setHint]=useState(false),c=builds[i];const pool=useMemo(()=>[...c.t,...c.x].map((w,j)=>({w,id:`${j}:${w}`})).sort(()=>.5-Math.random()),[c]);const check=()=>{const made=placed.map(x=>x.slice(x.indexOf(':')+1));if(made.join(' ')==c.t.join(' ')){setFb('ok');reward(20,`build-${i}`)}else setFb('no')};const next=()=>{setI((i+1)%builds.length);setPlaced([]);setFb(null);setHint(false)};return <section className="play"><Head title="בונים משפט" step="שלב 3" back={back}/><Meter now={i+1} total={builds.length} label="אתגר"/><section className="builder"><span>סדרי את המילים וכתבי באנגלית:</span><h2>״{c.he}״</h2>{hint&&<p className="hint"><Lightbulb/> המילה הראשונה היא: <b dir="ltr">{c.t[0]}</b></p>}<div className="zone" dir="ltr">{placed.length?placed.map(x=><button key={x} onClick={()=>{setPlaced(placed.filter(y=>y!==x));setFb(null)}}>{x.slice(x.indexOf(':')+1)}</button>):<span>לחצי על המילים לפי הסדר...</span>}</div><div className="bank" dir="ltr">{pool.filter(x=>!placed.includes(x.id)).map(x=><button key={x.id} onClick={()=>{setPlaced([...placed,x.id]);setFb(null)}}>{x.w}</button>)}</div><div className="tools"><button onClick={()=>setPlaced(placed.slice(0,-1))}><RotateCcw/> ביטול</button><button onClick={()=>setPlaced([])}><Eraser/> ניקוי</button><button onClick={()=>setHint(true)}><Lightbulb/> רמז</button></div>{fb&&<p className={'feedback '+fb}>{fb==='ok'?'🎉 בנית משפט מושלם!':'הסדר עדיין לא נכון. בדקי שוב את המילים'}</p>}<button className="primary" onClick={fb==='ok'?next:check}>{fb==='ok'?'לאתגר הבא':'בדיקת תשובה'} <Check/></button></section></section>}
function Progress({s,reset,back}:{s:Stats;reset:()=>void;back:()=>void}){const p=Math.min(100,Math.round(s.completed.length/TOTAL_ACTIVITIES*100));return <section className="play"><Head title="ההתקדמות שלי" step="כל הכבוד" back={back}/><section className="progress"><div>🏆</div><h2>{p<30?'התחלה נהדרת!':p<80?'את ממש מתקדמת!':'איזו אלופה!'}</h2><p>כל תשובה נכונה מחזקת את האנגלית שלך.</p><div className="bigbar"><i style={{width:`${p}%`}}/><b>{p}%</b></div><section><Stat icon={<Star/>} n={s.score} t="כוכבים"/><Stat icon={<BookOpen/>} n={s.wordsSeen} t="מילים שנצפו"/><Stat icon={<Trophy/>} n={s.completed.length} t="אתגרים שהושלמו"/><Stat icon={<Gamepad2/>} n={s.streak} t="רצף נוכחי"/></section><button className="soft" onClick={reset}><RotateCcw/> התחלה מחדש</button></section></section>}
function Stat({icon,n,t}:{icon:React.ReactNode;n:number;t:string}){return <div>{icon}<strong>{n}</strong><span>{t}</span></div>}
